version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: app_frontend
    depends_on:
    - backend
  backend:
    build: ./backend
    ports:
      - 3001:5000
    container_name: app_backend
    restart: 'always'
